### ISSUE TITLE
mGridPaint in class TimeChart not initialized?

### ISSUE THREAD

**Issue by RoqueCampos** [ddanny/achartengine#493]
Hi,

I'm using achartengine 1.2.0 and becoming the following exception:

```
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.Paint.setStyle(android.graphics.Paint$Style)' on a null object reference
                                                                           at org.achartengine.chart.TimeChart.drawXLabels(TimeChart.java:101)
                                                                           at org.achartengine.chart.XYChart.draw(XYChart.java:260)
```

Looking at the source code, I realized that the object is declared but never initialized. I suppose this is a bug...

Regards...

**Comment by EkoMcCloud** [comment]
Came here for the same thing, impossible to get Y grid lines on a TimeChart on version 1.2.0

I tried on 1.1.0 and it works better but now I'm missing setYLabelFormat function...
